version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - sacred

  omniboard:
    container_name: omniboard
    image: vivekratnavel/omniboard
    command: ["-m", "mongodb:27017:sacred"]
    networks:
      - sacred
    ports:
      - 9000:9000
    depends_on:
      - mongodb

networks:
  sacred:
